# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  taskmanagerapi:
    image: taskmanagerapi
    build:
      context: .
      dockerfile: TaskManager.Api/Dockerfile
    ports:
      - 80:80
