CREATE TABLE [dbo].[TASK_DISCUSSION]
(
  [Id] [int] NOT NULL,
  [Comment] [nvarchar](max) NOT NULL,
  [User] [nvarchar](320) NOT NULL,
  [TaskId] [int] NOT NULL,
  CONSTRAINT [PK_TASKDISCUSSION] PRIMARY KEY ([Id]),
  CONSTRAINT [FK_TASKDISCUSSION_USER] FOREIGN KEY([User]) REFERENCES [dbo].[USER] ([Id]),
  CONSTRAINT [FK_TASKDISCUSSION_TASK] FOREIGN KEY([TaskId]) REFERENCES [dbo].[TASK] ([Id])
)
